version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-nest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3390:3306"
      - "33900:33060"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    restart: always

  redis:
    image: bitnami/redis:latest
    container_name: redis-nest
    ports:
    - 6380:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - ./tmp/dump.rdb:/bitnami/redis/data/dump.rdb