version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3390:3306"
      - "33900:33060"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    restart: always