version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 3309:3306
      - 33090:33060
    restart: on-failure
